### ISSUE TITLE
Can't check current status of DPI and Hz

### ISSUE THREAD

**Issue by adojck** [Streetwalrus/da2013ctl#3]
Hello,
Thanks for this great tool! That shining logo on the mouse was pretty annoying me :) now I am really happy that I can turn it off.

My issue is that I can't check my mouse Sensor resolution and Polling rate. Not sure about current values. They should be default and I'm thinking I would like to increase sensor res and/or polling rate.

So it's a feature request, not a bug report.

Running Arch Linux with DeathAdder 2013 mouse.

**Comment by 9ary** [comment]
I don't think this is possible, as far as I know the official Razer software will simply reset the mouse to whatever setting it has in store, and track state internally.
