### ISSUE TITLE
Scroll speed?

### ISSUE THREAD

**Issue by donnex** [Streetwalrus/da2013ctl#5]
I successfully built and enabled the driver in Fedora 28 and everything is working great.

The only problem I'm having is about scroll speed. It's very slow for the moment. Is this something that could/should be supported in the driver? Maybe I've missed something but I haven't found a proper way to set the scroll speed in Gnome/Fedora and some posts suggested that it should be configured with the mouse driver.

**Comment by 9ary** [comment]
This isn't a driver, it's a utility to change the settings that are stored on the mouse itself, and everything is already exposed. Scrolling speed is determined by the application (each "click" of the wheel is a button press, and applications are free to do whatever they want with that).
